FROM debian:trixie

ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=${USER_UID}

ENV DEBIAN_FRONTEND=noninteractive
ENV PIP_DISABLE_PIP_VERSION_CHECK=1

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    bash-completion \
    build-essential \
    ca-certificates \
    clang \
    cmake \
    curl \
    gdb \
    git \
    gnuplot \
    ssh \
    less \
    libpapi-dev \
    libtinfo-dev \
    libz3-dev \
    lld \
    llvm-19 \
    llvm-19-dev \
    libpolly-19-dev \
    make \
    ninja-build \
    linux-perf \
    pkg-config \
    python3 \
    python3-dev \
    python3-pip \
    python3-venv \
    python3-pytest \
    sudo \
    time \
    zlib1g-dev \
    libzstd-dev \
    scons \
    && update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-19 100 \
    && update-alternatives --set llvm-config /usr/bin/llvm-config-19

RUN groupadd --gid "${USER_GID}" "${USERNAME}" \
    && useradd --uid "${USER_UID}" --gid "${USER_GID}" -m "${USERNAME}" --shell /bin/bash \
    && echo "${USERNAME} ALL=(root) NOPASSWD:ALL" > "/etc/sudoers.d/${USERNAME}" \
    && chmod 0440 "/etc/sudoers.d/${USERNAME}"

USER ${USERNAME}
WORKDIR /workspaces/symbolic-profiling

CMD ["/bin/bash"]
